name: clip_shadowx
description: A new Flutter project.
version: 0.0.1

repository: https://github.com/xErik/clip_shadowx
issue_tracker: https://github.com/xErik/clip_shadowx/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

